SimpleTest:
	g++ SimpleTest.cpp -I../.. -I../../../common -I ../../../lib ../../../lib/sqlite3/*.o ../*.cpp ../../../common/log/*.cpp -lpthread -ldl -o SimpleTest

InsertTest:
	g++ InsertTest.cpp -I../.. -I../../../common -I ../../../lib ../../../lib/sqlite3/*.o ../Connection.cpp ../Statement.cpp ../../../common/log/*.cpp -lpthread -ldl -o InsertTest
