XmlTest:
	g++ -g XmlTest.cpp -I../../ ../../log/*.cpp ../../sys/*.cpp ../../xml/*.cpp ../../util/*.cpp -lpthread -lrt -lxml2 -oXmlTest
TestXPath: TestXPath.cpp
	g++ -g TestXPath.cpp -I../../ ../../log/*.cpp ../../sys/*.cpp ../../xml/*.cpp ../../util/*.cpp -lpthread -lrt -lxml2 -oTestXPath
